# This specifies the version of the Docker Compose file format.
version: '3.8'

# The 'services' block is where we define each container of our application.
services:
  # --- The Go Backend Service ---
  backend:
    build: ./backend
    container_name: factcheck-backend
    ports:
      - "8080:8080"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
    # NEW: We mount our named volume to the directory inside the container
    # where the SQLite database is stored.
    volumes:
      - factcheck-data:/app/data

  # --- The Streamlit Frontend Service ---
  frontend:
    build: ./frontend
    container_name: factcheck-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend

# NEW: The top-level 'volumes' key is where we define our named volumes.
# This tells Docker to create and manage a persistent storage volume
# named 'factcheck-data'.
volumes:
  factcheck-data:
